//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from vhdl.g4 by ANTLR 4.9.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="vhdlParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.3")]
[System.CLSCompliant(false)]
public interface IvhdlVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.abstract_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAbstract_literal([NotNull] vhdlParser.Abstract_literalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.access_type_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAccess_type_definition([NotNull] vhdlParser.Access_type_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.across_aspect"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAcross_aspect([NotNull] vhdlParser.Across_aspectContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.actual_designator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitActual_designator([NotNull] vhdlParser.Actual_designatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.actual_parameter_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitActual_parameter_part([NotNull] vhdlParser.Actual_parameter_partContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.actual_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitActual_part([NotNull] vhdlParser.Actual_partContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.adding_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAdding_operator([NotNull] vhdlParser.Adding_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.aggregate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAggregate([NotNull] vhdlParser.AggregateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.alias_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlias_declaration([NotNull] vhdlParser.Alias_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.alias_designator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlias_designator([NotNull] vhdlParser.Alias_designatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.alias_indication"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlias_indication([NotNull] vhdlParser.Alias_indicationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.allocator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAllocator([NotNull] vhdlParser.AllocatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.architecture_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArchitecture_body([NotNull] vhdlParser.Architecture_bodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.architecture_declarative_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArchitecture_declarative_part([NotNull] vhdlParser.Architecture_declarative_partContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.architecture_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArchitecture_statement([NotNull] vhdlParser.Architecture_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.architecture_statement_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArchitecture_statement_part([NotNull] vhdlParser.Architecture_statement_partContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.array_nature_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray_nature_definition([NotNull] vhdlParser.Array_nature_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.array_type_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray_type_definition([NotNull] vhdlParser.Array_type_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.assertion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssertion([NotNull] vhdlParser.AssertionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.assertion_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssertion_statement([NotNull] vhdlParser.Assertion_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.association_element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssociation_element([NotNull] vhdlParser.Association_elementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.association_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssociation_list([NotNull] vhdlParser.Association_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.attribute_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttribute_declaration([NotNull] vhdlParser.Attribute_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.attribute_designator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttribute_designator([NotNull] vhdlParser.Attribute_designatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.attribute_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttribute_specification([NotNull] vhdlParser.Attribute_specificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.base_unit_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBase_unit_declaration([NotNull] vhdlParser.Base_unit_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.binding_indication"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinding_indication([NotNull] vhdlParser.Binding_indicationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.block_configuration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock_configuration([NotNull] vhdlParser.Block_configurationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.block_declarative_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock_declarative_item([NotNull] vhdlParser.Block_declarative_itemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.block_declarative_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock_declarative_part([NotNull] vhdlParser.Block_declarative_partContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.block_header"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock_header([NotNull] vhdlParser.Block_headerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.block_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock_specification([NotNull] vhdlParser.Block_specificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.block_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock_statement([NotNull] vhdlParser.Block_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.block_statement_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock_statement_part([NotNull] vhdlParser.Block_statement_partContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.branch_quantity_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBranch_quantity_declaration([NotNull] vhdlParser.Branch_quantity_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.break_element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBreak_element([NotNull] vhdlParser.Break_elementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.break_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBreak_list([NotNull] vhdlParser.Break_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.break_selector_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBreak_selector_clause([NotNull] vhdlParser.Break_selector_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.break_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBreak_statement([NotNull] vhdlParser.Break_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.case_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCase_statement([NotNull] vhdlParser.Case_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.case_statement_alternative"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCase_statement_alternative([NotNull] vhdlParser.Case_statement_alternativeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.choice"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitChoice([NotNull] vhdlParser.ChoiceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.choices"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitChoices([NotNull] vhdlParser.ChoicesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.component_configuration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComponent_configuration([NotNull] vhdlParser.Component_configurationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.component_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComponent_declaration([NotNull] vhdlParser.Component_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.component_instantiation_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComponent_instantiation_statement([NotNull] vhdlParser.Component_instantiation_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.component_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComponent_specification([NotNull] vhdlParser.Component_specificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.composite_nature_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComposite_nature_definition([NotNull] vhdlParser.Composite_nature_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.composite_type_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComposite_type_definition([NotNull] vhdlParser.Composite_type_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.concurrent_assertion_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConcurrent_assertion_statement([NotNull] vhdlParser.Concurrent_assertion_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.concurrent_break_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConcurrent_break_statement([NotNull] vhdlParser.Concurrent_break_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.concurrent_procedure_call_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConcurrent_procedure_call_statement([NotNull] vhdlParser.Concurrent_procedure_call_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.concurrent_signal_assignment_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConcurrent_signal_assignment_statement([NotNull] vhdlParser.Concurrent_signal_assignment_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCondition([NotNull] vhdlParser.ConditionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.condition_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCondition_clause([NotNull] vhdlParser.Condition_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.conditional_signal_assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditional_signal_assignment([NotNull] vhdlParser.Conditional_signal_assignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.conditional_waveforms"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditional_waveforms([NotNull] vhdlParser.Conditional_waveformsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.configuration_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConfiguration_declaration([NotNull] vhdlParser.Configuration_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.configuration_declarative_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConfiguration_declarative_item([NotNull] vhdlParser.Configuration_declarative_itemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.configuration_declarative_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConfiguration_declarative_part([NotNull] vhdlParser.Configuration_declarative_partContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.configuration_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConfiguration_item([NotNull] vhdlParser.Configuration_itemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.configuration_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConfiguration_specification([NotNull] vhdlParser.Configuration_specificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.constant_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstant_declaration([NotNull] vhdlParser.Constant_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.constrained_array_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstrained_array_definition([NotNull] vhdlParser.Constrained_array_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.constrained_nature_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstrained_nature_definition([NotNull] vhdlParser.Constrained_nature_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstraint([NotNull] vhdlParser.ConstraintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.context_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContext_clause([NotNull] vhdlParser.Context_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.context_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContext_item([NotNull] vhdlParser.Context_itemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.delay_mechanism"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDelay_mechanism([NotNull] vhdlParser.Delay_mechanismContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.design_file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDesign_file([NotNull] vhdlParser.Design_fileContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.design_unit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDesign_unit([NotNull] vhdlParser.Design_unitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.designator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDesignator([NotNull] vhdlParser.DesignatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.direction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDirection([NotNull] vhdlParser.DirectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.disconnection_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDisconnection_specification([NotNull] vhdlParser.Disconnection_specificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.discrete_range"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDiscrete_range([NotNull] vhdlParser.Discrete_rangeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.element_association"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElement_association([NotNull] vhdlParser.Element_associationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.element_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElement_declaration([NotNull] vhdlParser.Element_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.element_subnature_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElement_subnature_definition([NotNull] vhdlParser.Element_subnature_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.element_subtype_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElement_subtype_definition([NotNull] vhdlParser.Element_subtype_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.entity_aspect"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntity_aspect([NotNull] vhdlParser.Entity_aspectContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.entity_class"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntity_class([NotNull] vhdlParser.Entity_classContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.entity_class_entry"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntity_class_entry([NotNull] vhdlParser.Entity_class_entryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.entity_class_entry_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntity_class_entry_list([NotNull] vhdlParser.Entity_class_entry_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.entity_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntity_declaration([NotNull] vhdlParser.Entity_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.entity_declarative_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntity_declarative_item([NotNull] vhdlParser.Entity_declarative_itemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.entity_declarative_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntity_declarative_part([NotNull] vhdlParser.Entity_declarative_partContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.entity_designator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntity_designator([NotNull] vhdlParser.Entity_designatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.entity_header"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntity_header([NotNull] vhdlParser.Entity_headerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.entity_name_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntity_name_list([NotNull] vhdlParser.Entity_name_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.entity_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntity_specification([NotNull] vhdlParser.Entity_specificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.entity_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntity_statement([NotNull] vhdlParser.Entity_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.entity_statement_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntity_statement_part([NotNull] vhdlParser.Entity_statement_partContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.entity_tag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntity_tag([NotNull] vhdlParser.Entity_tagContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.enumeration_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumeration_literal([NotNull] vhdlParser.Enumeration_literalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.enumeration_type_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumeration_type_definition([NotNull] vhdlParser.Enumeration_type_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.exit_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExit_statement([NotNull] vhdlParser.Exit_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] vhdlParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFactor([NotNull] vhdlParser.FactorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.file_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFile_declaration([NotNull] vhdlParser.File_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.file_logical_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFile_logical_name([NotNull] vhdlParser.File_logical_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.file_open_information"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFile_open_information([NotNull] vhdlParser.File_open_informationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.file_type_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFile_type_definition([NotNull] vhdlParser.File_type_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.formal_parameter_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFormal_parameter_list([NotNull] vhdlParser.Formal_parameter_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.formal_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFormal_part([NotNull] vhdlParser.Formal_partContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.free_quantity_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFree_quantity_declaration([NotNull] vhdlParser.Free_quantity_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.generate_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGenerate_statement([NotNull] vhdlParser.Generate_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.generation_scheme"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeneration_scheme([NotNull] vhdlParser.Generation_schemeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.generic_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeneric_clause([NotNull] vhdlParser.Generic_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.generic_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeneric_list([NotNull] vhdlParser.Generic_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.generic_map_aspect"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeneric_map_aspect([NotNull] vhdlParser.Generic_map_aspectContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.group_constituent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGroup_constituent([NotNull] vhdlParser.Group_constituentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.group_constituent_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGroup_constituent_list([NotNull] vhdlParser.Group_constituent_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.group_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGroup_declaration([NotNull] vhdlParser.Group_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.group_template_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGroup_template_declaration([NotNull] vhdlParser.Group_template_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.guarded_signal_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGuarded_signal_specification([NotNull] vhdlParser.Guarded_signal_specificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier([NotNull] vhdlParser.IdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.identifier_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier_list([NotNull] vhdlParser.Identifier_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.if_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf_statement([NotNull] vhdlParser.If_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.index_constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndex_constraint([NotNull] vhdlParser.Index_constraintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.index_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndex_specification([NotNull] vhdlParser.Index_specificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.index_subtype_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndex_subtype_definition([NotNull] vhdlParser.Index_subtype_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.instantiated_unit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstantiated_unit([NotNull] vhdlParser.Instantiated_unitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.instantiation_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstantiation_list([NotNull] vhdlParser.Instantiation_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.interface_constant_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterface_constant_declaration([NotNull] vhdlParser.Interface_constant_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.interface_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterface_declaration([NotNull] vhdlParser.Interface_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.interface_element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterface_element([NotNull] vhdlParser.Interface_elementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.interface_file_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterface_file_declaration([NotNull] vhdlParser.Interface_file_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.interface_signal_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterface_signal_list([NotNull] vhdlParser.Interface_signal_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.interface_port_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterface_port_list([NotNull] vhdlParser.Interface_port_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.interface_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterface_list([NotNull] vhdlParser.Interface_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.interface_quantity_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterface_quantity_declaration([NotNull] vhdlParser.Interface_quantity_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.interface_port_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterface_port_declaration([NotNull] vhdlParser.Interface_port_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.interface_signal_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterface_signal_declaration([NotNull] vhdlParser.Interface_signal_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.interface_terminal_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterface_terminal_declaration([NotNull] vhdlParser.Interface_terminal_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.interface_variable_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterface_variable_declaration([NotNull] vhdlParser.Interface_variable_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.iteration_scheme"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIteration_scheme([NotNull] vhdlParser.Iteration_schemeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.label_colon"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLabel_colon([NotNull] vhdlParser.Label_colonContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.library_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLibrary_clause([NotNull] vhdlParser.Library_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.library_unit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLibrary_unit([NotNull] vhdlParser.Library_unitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral([NotNull] vhdlParser.LiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.logical_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogical_name([NotNull] vhdlParser.Logical_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.logical_name_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogical_name_list([NotNull] vhdlParser.Logical_name_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.logical_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogical_operator([NotNull] vhdlParser.Logical_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.loop_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLoop_statement([NotNull] vhdlParser.Loop_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.signal_mode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSignal_mode([NotNull] vhdlParser.Signal_modeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.multiplying_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiplying_operator([NotNull] vhdlParser.Multiplying_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitName([NotNull] vhdlParser.NameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.name_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitName_part([NotNull] vhdlParser.Name_partContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.name_attribute_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitName_attribute_part([NotNull] vhdlParser.Name_attribute_partContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.name_function_call_or_indexed_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitName_function_call_or_indexed_part([NotNull] vhdlParser.Name_function_call_or_indexed_partContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.name_slice_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitName_slice_part([NotNull] vhdlParser.Name_slice_partContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.selected_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelected_name([NotNull] vhdlParser.Selected_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.nature_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNature_declaration([NotNull] vhdlParser.Nature_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.nature_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNature_definition([NotNull] vhdlParser.Nature_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.nature_element_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNature_element_declaration([NotNull] vhdlParser.Nature_element_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.next_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNext_statement([NotNull] vhdlParser.Next_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.numeric_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumeric_literal([NotNull] vhdlParser.Numeric_literalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.object_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObject_declaration([NotNull] vhdlParser.Object_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.opts"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpts([NotNull] vhdlParser.OptsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.package_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPackage_body([NotNull] vhdlParser.Package_bodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.package_body_declarative_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPackage_body_declarative_item([NotNull] vhdlParser.Package_body_declarative_itemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.package_body_declarative_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPackage_body_declarative_part([NotNull] vhdlParser.Package_body_declarative_partContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.package_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPackage_declaration([NotNull] vhdlParser.Package_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.package_declarative_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPackage_declarative_item([NotNull] vhdlParser.Package_declarative_itemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.package_declarative_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPackage_declarative_part([NotNull] vhdlParser.Package_declarative_partContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.parameter_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameter_specification([NotNull] vhdlParser.Parameter_specificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.physical_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPhysical_literal([NotNull] vhdlParser.Physical_literalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.physical_type_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPhysical_type_definition([NotNull] vhdlParser.Physical_type_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.port_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPort_clause([NotNull] vhdlParser.Port_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.port_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPort_list([NotNull] vhdlParser.Port_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.port_map_aspect"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPort_map_aspect([NotNull] vhdlParser.Port_map_aspectContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimary([NotNull] vhdlParser.PrimaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.primary_unit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimary_unit([NotNull] vhdlParser.Primary_unitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.procedural_declarative_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProcedural_declarative_item([NotNull] vhdlParser.Procedural_declarative_itemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.procedural_declarative_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProcedural_declarative_part([NotNull] vhdlParser.Procedural_declarative_partContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.procedural_statement_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProcedural_statement_part([NotNull] vhdlParser.Procedural_statement_partContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.procedure_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProcedure_call([NotNull] vhdlParser.Procedure_callContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.procedure_call_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProcedure_call_statement([NotNull] vhdlParser.Procedure_call_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.process_declarative_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProcess_declarative_item([NotNull] vhdlParser.Process_declarative_itemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.process_declarative_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProcess_declarative_part([NotNull] vhdlParser.Process_declarative_partContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.process_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProcess_statement([NotNull] vhdlParser.Process_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.process_statement_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProcess_statement_part([NotNull] vhdlParser.Process_statement_partContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.qualified_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQualified_expression([NotNull] vhdlParser.Qualified_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.quantity_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQuantity_declaration([NotNull] vhdlParser.Quantity_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.quantity_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQuantity_list([NotNull] vhdlParser.Quantity_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.quantity_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQuantity_specification([NotNull] vhdlParser.Quantity_specificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.range_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRange_decl([NotNull] vhdlParser.Range_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.explicit_range"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExplicit_range([NotNull] vhdlParser.Explicit_rangeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.range_constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRange_constraint([NotNull] vhdlParser.Range_constraintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.record_nature_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRecord_nature_definition([NotNull] vhdlParser.Record_nature_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.record_type_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRecord_type_definition([NotNull] vhdlParser.Record_type_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.relation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelation([NotNull] vhdlParser.RelationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.relational_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelational_operator([NotNull] vhdlParser.Relational_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.report_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReport_statement([NotNull] vhdlParser.Report_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.return_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturn_statement([NotNull] vhdlParser.Return_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.scalar_nature_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitScalar_nature_definition([NotNull] vhdlParser.Scalar_nature_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.scalar_type_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitScalar_type_definition([NotNull] vhdlParser.Scalar_type_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.secondary_unit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSecondary_unit([NotNull] vhdlParser.Secondary_unitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.secondary_unit_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSecondary_unit_declaration([NotNull] vhdlParser.Secondary_unit_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.selected_signal_assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelected_signal_assignment([NotNull] vhdlParser.Selected_signal_assignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.selected_waveforms"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelected_waveforms([NotNull] vhdlParser.Selected_waveformsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.sensitivity_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSensitivity_clause([NotNull] vhdlParser.Sensitivity_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.sensitivity_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSensitivity_list([NotNull] vhdlParser.Sensitivity_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.sequence_of_statements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSequence_of_statements([NotNull] vhdlParser.Sequence_of_statementsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.sequential_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSequential_statement([NotNull] vhdlParser.Sequential_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.shift_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShift_expression([NotNull] vhdlParser.Shift_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.shift_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShift_operator([NotNull] vhdlParser.Shift_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.signal_assignment_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSignal_assignment_statement([NotNull] vhdlParser.Signal_assignment_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.signal_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSignal_declaration([NotNull] vhdlParser.Signal_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.signal_kind"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSignal_kind([NotNull] vhdlParser.Signal_kindContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.signal_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSignal_list([NotNull] vhdlParser.Signal_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.signature"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSignature([NotNull] vhdlParser.SignatureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.simple_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimple_expression([NotNull] vhdlParser.Simple_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.simple_simultaneous_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimple_simultaneous_statement([NotNull] vhdlParser.Simple_simultaneous_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.simultaneous_alternative"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimultaneous_alternative([NotNull] vhdlParser.Simultaneous_alternativeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.simultaneous_case_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimultaneous_case_statement([NotNull] vhdlParser.Simultaneous_case_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.simultaneous_if_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimultaneous_if_statement([NotNull] vhdlParser.Simultaneous_if_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.simultaneous_procedural_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimultaneous_procedural_statement([NotNull] vhdlParser.Simultaneous_procedural_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.simultaneous_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimultaneous_statement([NotNull] vhdlParser.Simultaneous_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.simultaneous_statement_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimultaneous_statement_part([NotNull] vhdlParser.Simultaneous_statement_partContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.source_aspect"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSource_aspect([NotNull] vhdlParser.Source_aspectContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.source_quantity_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSource_quantity_declaration([NotNull] vhdlParser.Source_quantity_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.step_limit_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStep_limit_specification([NotNull] vhdlParser.Step_limit_specificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.subnature_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubnature_declaration([NotNull] vhdlParser.Subnature_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.subnature_indication"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubnature_indication([NotNull] vhdlParser.Subnature_indicationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.subprogram_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubprogram_body([NotNull] vhdlParser.Subprogram_bodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.subprogram_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubprogram_declaration([NotNull] vhdlParser.Subprogram_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.subprogram_declarative_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubprogram_declarative_item([NotNull] vhdlParser.Subprogram_declarative_itemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.subprogram_declarative_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubprogram_declarative_part([NotNull] vhdlParser.Subprogram_declarative_partContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.subprogram_kind"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubprogram_kind([NotNull] vhdlParser.Subprogram_kindContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.subprogram_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubprogram_specification([NotNull] vhdlParser.Subprogram_specificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.procedure_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProcedure_specification([NotNull] vhdlParser.Procedure_specificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.function_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_specification([NotNull] vhdlParser.Function_specificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.subprogram_statement_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubprogram_statement_part([NotNull] vhdlParser.Subprogram_statement_partContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.subtype_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubtype_declaration([NotNull] vhdlParser.Subtype_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.subtype_indication"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubtype_indication([NotNull] vhdlParser.Subtype_indicationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.suffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSuffix([NotNull] vhdlParser.SuffixContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.target"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTarget([NotNull] vhdlParser.TargetContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm([NotNull] vhdlParser.TermContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.terminal_aspect"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerminal_aspect([NotNull] vhdlParser.Terminal_aspectContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.terminal_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerminal_declaration([NotNull] vhdlParser.Terminal_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.through_aspect"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThrough_aspect([NotNull] vhdlParser.Through_aspectContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.timeout_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTimeout_clause([NotNull] vhdlParser.Timeout_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.tolerance_aspect"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTolerance_aspect([NotNull] vhdlParser.Tolerance_aspectContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.type_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_declaration([NotNull] vhdlParser.Type_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.type_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_definition([NotNull] vhdlParser.Type_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.unconstrained_array_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnconstrained_array_definition([NotNull] vhdlParser.Unconstrained_array_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.unconstrained_nature_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnconstrained_nature_definition([NotNull] vhdlParser.Unconstrained_nature_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.use_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUse_clause([NotNull] vhdlParser.Use_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.variable_assignment_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable_assignment_statement([NotNull] vhdlParser.Variable_assignment_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.conditional_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditional_expression([NotNull] vhdlParser.Conditional_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.variable_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable_declaration([NotNull] vhdlParser.Variable_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.wait_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWait_statement([NotNull] vhdlParser.Wait_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.waveform"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWaveform([NotNull] vhdlParser.WaveformContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="vhdlParser.waveform_element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWaveform_element([NotNull] vhdlParser.Waveform_elementContext context);
}
